name: pypi

on:
  push:
    branches:
      - enable_azure

jobs:
  Windows:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]  
    runs-on: windows-2019
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
