name: pypi

on:
  push:
    branches:
      - enable_azure

jobs:
  example_matrix:
    strategy:
      matrix:
        PYTHON:
          - VERSION_SPEC: 3.7
            TAG: cp36
  Windows:
    runs-on: windows-2019
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON.VERSION_SPEC }}
          check-latest: false
      - run: |
          python -m pip install --upgrade pip
