name: pypi

on:
  push:
    branches:
      - enable_azure

jobs:
  Windows:
    strategy:
      matrix:
        PYTHON:
          - VERSION_SPEC: 3.7
            TAG: cp37
    runs-on: windows-2019
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON.VERSION_SPEC }}
