name: pypi

on:
  push:
    branches:
      - enable_azure

jobs:
  Windows:
    strategy:
      matrix:
        PYTHON:
          - VERSION_SPEC: 3.6
            TAG: cp36
          - VERSION_SPEC: 3.7
            TAG: cp37
          - VERSION_SPEC: 3.8
            TAG: cp38
          - VERSION_SPEC: 3.9
            TAG: cp39
          - VERSION_SPEC: 3.10
            TAG: cp310
          - VERSION_SPEC: 3.11
            TAG: cp311
    runs-on: windows-2019
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON.VERSION_SPEC }}
      - name: Build USD
        run: |
          echo
